name: media_kit_win_mem_test
description: media_kit mem leak test for windows
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  media_kit:
    path: ../media-kit/media_kit
  media_kit_video:
    path: ../media-kit/media_kit_video
  media_kit_native_event_loop:
    path: ../media-kit/media_kit_native_event_loop
  media_kit_libs_linux: ^1.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/video_0.mp4
    - assets/amazon_dog.mp4
    - assets/bulgari.mp4
    - assets/cocacola_one.mp4
    - assets/cocacola_two.mp4
    - assets/hersheys.mp4
    - assets/kwality_walls.mp4
    - assets/pepsi_peeps.mp4
    - assets/pepsi_three.mp4
    - assets/pepsi_two.mp4
    - assets/tiffanyco.mp4
    - assets/tiffanyco_two.mp4
    - assets/uniqlo.mp4
